<?php
$allstates = array(
  'AK' => 'Alaska',
  'AL' => 'Alabama',
  'AR' => 'Arkansas',
  'AZ' => 'Arizona',
  'CA' => 'California',
  'CO' => 'Colorado',
  'CT' => 'Connecticut',
  'DE' => 'Delaware',
  'FL' => 'Florida',
  'GA' => 'Georgia',
  'HI' => 'Hawaii',
  'IA' => 'Iowa',
  'ID' => 'Idaho',
  'IL' => 'Illinois',
  'IN' => 'Indiana',
  'KS' => 'Kansas',
  'KY' => 'Kentucky',
  'LA' => 'Louisiana',
  'MA' => 'Massachusetts',
  'MD' => 'Maryland',
  'ME' => 'Maine',
  'MI' => 'Michigan',
  'MN' => 'Minnesota',
  'MO' => 'Missouri',
  'MS' => 'Mississippi',
  'MT' => 'Montana',
  'NC' => 'North Carolina',
  'ND' => 'North Dakota',
  'NE' => 'Nebraska',
  'NH' => 'New Hampshire',
  'NJ' => 'New Jersey',
  'NM' => 'New Mexico',
  'NV' => 'Nevada',
  'NY' => 'New York',
  'OH' => 'Ohio',
  'OK' => 'Oklahoma',
  'OR' => 'Oregon',
  'PA' => 'Pennsylvania',
  'RI' => 'Rhode Island',
  'SC' => 'South Carolina',
  'SD' => 'South Dakota',
  'TN' => 'Tennessee',
  'TX' => 'Texas',
  'UT' => 'Utah',
  'VA' => 'Virginia',
  'VT' => 'Vermont',
  'WA' => 'Washington',
  'WI' => 'Wisconsin',
  'WV' => 'West Virginia',
  'WY' => 'Wyoming');

$deed = array(
  'CA',
  'OR',
  'WA',
  'NV',
  'ID',
  'UT',
  'NM',
  'AK',
  'ND',
  'SD',
  'KS',
  'OK',
  'MN',
  'WI',
  'MI',
  'AR',
  'OH',
  'PA',
  'NY',
  'ME',
  'NH',
  'MD',
  'VA',
  'NC');

$rdeed = array(
  'TX');

$lien = array(
  'MT',
  'WY',
  'CO',
  'AZ',
  'HI',
  'NE',
  'IA',
  'MO',
  'IL',
  'IN',
  'LA',
  'MS',
  'AL',
  'SC',
  'WV',
  'NJ',
  'DC');

$hybrid = array(
  'RI',
  'CT',
  'VT',
  'DE',
  'MA',
  'KY',
  'TN',
  'GA',
  'FL');
?>